kind: pipeline
type: docker

steps:
  - name: lint
    image: alpine
    commands:
      - echo "Running linting step"

  - name: test
    image: alpine
    commands:
      - echo "Running testing step"

  - name: build
    image: alpine
    commands:
      - echo "Running build step"

  - name: deploy-dev
    image: alpine
    commands:
      - echo "Deploying to dev environment"

  - name: deploy-prod
    image: alpine
    commands:
      - echo "Deploying to prod environment"