---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
- name: hello
  image: busybox
  commands:
  - echo AWESOME_PIPELINE_HERE

trigger:
  branch:
  - main

---
kind: pipeline
type: docker
name: default2

platform:
  os: linux
  arch: arm64

steps:
- name: test
  image: alpine
  commands:
  - echo IT_GOES_DEEPER

---
kind: pipeline
type: docker
name: default3

steps:
- name: test
  image: golang:1.13
  commands:
  - go build
  - go test -v

