---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
- name: hello
  image: busybox
  commands:
  - echo AWESOME_PIPELINE_HERE

trigger:
  branch:
  - main

---
kind: pipeline
type: docker
name: default2

platform:
  os: linux
  arch: arm64

steps:
- name: test
  image: gcr.io/library/golang
  commands:
  - go build
  - go test -v