---
kind: pipeline
type: docker
name: updater

steps:
  - name: hello
    image: alpine
    commands:
      - echo "Setting up the pipeline"

  - name: write
    image: alpine
    environment: 
      TEST_SECRET:
        from_secret: testsecret
    commands:
      - echo "export SECRET=$TEST_SECRET" > sourceme
      - echo "export SOMEVAR=somevalue" >> sourceme

  - name: read
    image: alpine
    commands:
      - source sourceme
      - env

  - name: cleanup
    image: alpine
    commands:
      - rm -rf build/
      - echo "Cleanup completed"
 
trigger:
  branch:
  - main
