kind: pipeline
type: docker

steps:
  - name: lint
    image: node:14
    commands:
      - npm install
      - npm run lint

  - name: test
    image: node:14
    commands:
      - npm install
      - npm run test

  - name: build
    image: node:14
    commands:
      - npm install
      - npm run build

  - name: dockerize
    image: docker:latest
    commands:
      - docker build -t myapp .
      - docker push myapp:latest

  - name: deploy
    image: gcr.io/cloud-builders/gcloud
    commands:
      - gcloud auth configure-docker
      - gcloud container clusters get-credentials my-cluster --region us-central1
      - kubectl apply -f deployment.yaml

  - name: hello
    image: busybox
    commands:
      - echo NEW_AWESOME_PIPELINE_JUST_GOT_EXECUTED!
