---
kind: pipeline
type: docker
name: pipeline

steps:
  - name: stepone
    image: alpine
    commands:
      - echo "Setting up the pipeline"

  - name: write2
    image: alpine
    environment: 
      TEST_SECRET:
        from_secret: testsecret
    commands:
      - echo "SECRET=$TEST_SECRET" > sourceme
      - echo "SOMEVAR=somevalue" >> sourceme

  - name: read3
    image: alpine
    commands:
      - source sourceme
      - env


  - name: cleanup
    image: alpine
    commands:
      - rm -rf build/
      - echo "Cleanup completed"
 
trigger:
  branch:
  - main