kind: pipeline
type: docker
name: drone-ci-pipeline

steps:
  - name: checkout
    image: alpine/git
    pull: always
    settings:
      clone:
        depth: 1
    commands:
      - git clone <repository-url> .
      - git checkout <branch>

  - name: build
    image: node:lts
    pull: always
    commands:
      - npm install
      - npm run build

  - name: test
    image: node:lts
    pull: always
    commands:
      - npm test

  - name: generate-artifacts
    image: node:lts
    pull: always
    commands:
      - npm run generate-artifacts

  - name: deploy
    image: <deployment-image>
    pull: always
    commands:
      - ./deploy.sh
